---
- name: Docker installation
  hosts: all
  become: true
  tasks:
     - name: Install docker
       ansible.builtin.apt:
          update_cache: true
          package:
             - docker.io

     - name: Start docker
       ansible.builtin.service:
          name: docker
          state: started

     - name: Run register container
       community.docker.docker_container:
          name: register
          state: started
          image: 'fteychene/cloud-cadavre-exquis-register:1.0-SNAPSHOT'
          ports:
             - '8080:8080'
          env:
             REGISTER_URLS: 'http://172.17.0.1:8081'

- name: Postgresql installation
  hosts: all
  become: true
  tasks:
     - name: Install postgresql
       ansible.builtin.apt:
          update_cache: true
          package:
             - postgresql
             - postgresql-contrib
     - name: Start postgresql
       ansible.builtin.service:
          name: postgresql
          state: started

     - name: Create database
       community.postgresql.postgresql_db:
          name: cadavre
          state: present

     - name: Create user
       community.postgresql.postgresql_user:
          name: cadavre
          password: cadavre
          priv: '*.*:ALL'
          state: present
