---
- name: Docker installation and service management
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started

    - name: Déploiement du service dispatcher
      docker_container:
        name: dispatcher
        image: fteychene/cloud-cadavre-exquis-dispatcher:1.0-SNAPSHOT
        env:
          REGISTER_URLS: "{{provider_instance_ip}}"  # "http://registers:8080"

    - name: Déploiement du service lb
      docker_container:
        name: lb
        image: nginx:1.19
        ports:
          - "8080:80"
        volumes:
          - "{{ playbook_dir }}/docker/nginx.conf:/etc/nginx/conf.d/default.conf"
