---
- name: Docker installation
  hosts: all
  become: true
  tasks:
     - name: Install docker
       ansible.builtin.apt:
          update_cache: true
          package:
             - docker.io

     - name: Start docker
       ansible.builtin.service:
          name: docker
          state: started

     - name: Run register container
       community.docker.docker_container:
          name: register
          state: started
          image: 'fteychene/cloud-cadavre-exquis-register:1.0-SNAPSHOT'
          ports:
             - '8080:8080'
          env:
            REGISTER_URLS: 'http://{{register_instance_ip}}:8080'
