---
- name: Docker installation
  hosts: all
  become: true
  tasks:
     - name: Install docker
       ansible.builtin.apt:
          update_cache: true
          package:
             - docker.io

     - name: Start docker
       ansible.builtin.service:
          name: docker
          state: started
     - name: Run register container
       community.docker.docker_container:
          name: db
          state: started
          image: 'postgres'
          ports:
             - '5432:5432'
          env:
             POSTGRES_USER: "test"
             POSTGRES_PASSWORD: "password"
             POSTGRES_DB: "register"

     - name: Run register container
       community.docker.docker_container:
          name: register
          state: started
          image: 'fteychene/cloud-cadavre-exquis-register:1.0-SNAPSHOT'
          ports:
             - '8080:8080'
          env:
             POSTGRESQL_ADDON_HOST: "postgres"
             POSTGRESQL_ADDON_PORT: "5432"
             POSTGRESQL_ADDON_DB: "register"
             POSTGRESQL_ADDON_USER: "test"
             POSTGRESQL_ADDON_PASSWORD: "password"
