---
- name: Docker installation
  hosts: all
  become: true
  tasks:
     - name: Install docker
       ansible.builtin.apt:
          update_cache: true
          package:
             - docker.io

     - name: Start docker
       ansible.builtin.service:
          name: docker
          state: started

     - name: Run provider subject container
       community.docker.docker_container:
          name: provider-subject
          state: started
          image: 'fteychene/cloud-cadavre-exquis-provider:1.0-SNAPSHOT'
          env:
             REGISTER_URLS: 'http://{{register_instance_ip}}:8080'
             WORD_TYPE: SUBJECT
     
     - name: Run provider verb container
       community.docker.docker_container:
          name: provider-verb
          state: started
          image: 'fteychene/cloud-cadavre-exquis-provider:1.0-SNAPSHOT'
          env:
             REGISTER_URLS: 'http://{{register_instance_ip}}:8080'
             WORD_TYPE: VERB
     
     - name: Run provider adjective container
       community.docker.docker_container:
          name: provider-adjective
          state: started
          image: 'fteychene/cloud-cadavre-exquis-provider:1.0-SNAPSHOT'
          env:
             REGISTER_URLS: 'http://{{register_instance_ip}}:8080'
             WORD_TYPE: ADJECTIVE
